Environmental_survey/Models/contact.cs
using System.ComponentModel.DataAnnotations;

namespace Environmental_survey.Models
{
    public class contact
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

Environmental_survey/Models/register.cs
using System.ComponentModel.DataAnnotations;

namespace Environmental_survey.Models
{
    public class register
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

Environmental_survey/Controllers/adminController.cs
using Environmental_survey.Data;
using Environmental_survey.Migrations;
using Environmental_survey.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Environmental_survey.Controllers
{
    public class adminController : Controller
    {
        appcontext _appcontext;

        // Image Work
        IWebHostEnvironment env;

        public adminController(appcontext appcontext, IWebHostEnvironment environment)
        {
            _appcontext = appcontext;
            env = environment ; 
        }


        // Temlate Work Start

        // Simple Views
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        
        public IActionResult Blog_Details()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        // Contact Insert
        [HttpPost]
        //public IActionResult Contact(contact c)
        //{
        //    _appcontext.contacts.Add(c);
        //    _appcontext.SaveChanges();
        //    ModelState.Clear();
        //    return View();
        //}

        public IActionResult Elements()
        {
            return View();
        }

        public IActionResult Project()
        {
            return View();

        }

        public IActionResult whatdo()
        {
            return View();
        }
        // Simple Views End


        // View
        public IActionResult Register()
        {
            return View();
        }

        // Register Insert
        [HttpPost]
        public IActionResult Register(register r)

        {
            _appcontext.registers.Add(r);
            _appcontext.SaveChanges();
            ModelState.Clear();
            return RedirectToAction("login");
        }

        // View
        public IActionResult login()
        {
            return View();
        }

        // Login Work
        [HttpPost]
        public IActionResult login(register r)
        {

            var a = _appcontext.registers.Where(data => data.Email == r.Email && data.Password == r.Password).FirstOrDefault();

            if (a != null)
            {
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.ErrorMessage = "Plz Insert Correct Password";
            }


            return View();
        }

        // Temlate Work End

        // Admin Dashboard Work End
        public IActionResult Dashboard()
        {
            return View();
        }


        // Contact Work Start

        // Fetch
        public IActionResult viewContact()
        {
            return View(_appcontext.contacts.ToList());
        }

        // Delete
        //public IActionResult contactDelete(int Id)
        //{
        //    contact c = _appcontext.contacts.Find(Id);
        //    _appcontext.contacts.Remove(c);
        //    _appcontext.SaveChanges();
        //    return RedirectToAction("viewContact");

        //}
        // Contact Work End


        // Signup Work Start

        // Fetch
        public IActionResult viewSignup()
        {
            return View(_appcontext.registers.ToList());
        }

        // Delete
        public IActionResult signupDelete(int Id)
        {
            register re = _appcontext.registers.Find(Id);
            _appcontext.registers.Remove(re);
            _appcontext.SaveChanges();
            return RedirectToAction("viewSignup");
        }

        // Update
        public IActionResult signupUpdate(int Id)
        {
            var mysignupupdate = _appcontext.registers.Find(Id);
            return View(mysignupupdate);
        }

        // Update(insert)
        [HttpPost]
        public IActionResult signupUpdate(register r)
        {
            var merasignupdate = _appcontext.registers.Find(r.Id);

            if(merasignupdate != null)
            {
                merasignupdate.Name = r.Name;
                merasignupdate.Email = r.Email;
                merasignupdate.Password = r.Password;
            }
            _appcontext.SaveChanges();

            return RedirectToAction("viewSignup");
        }

        // Signup Work End

        // Survey Work Start

        // View
        public IActionResult addSurvey()

        {
            return View();
        }

        // Insert + Img
        [HttpPost]
        public IActionResult addSurvey(survey_ s)

        {
            String filename = "";
            if (s.Photo != null)
            {
                String uploadFolder = Path.Combine(env.WebRootPath, "images");
                filename = Guid.NewGuid().ToString() + "_" + s.Photo.FileName;
                String mergevalue = Path.Combine(uploadFolder, filename);
                s.Photo.CopyTo(new FileStream(mergevalue, FileMode.Create));
                Survey data = new Survey
                {
                    Title = s.Title,
                    Details  = s.Details,
                    SurveyImage = filename
                };
                _appcontext.surveys.Add(data);
                _appcontext.SaveChanges();
                ModelState.Clear();
            }
            return RedirectToAction("Dashboard");
           
        }

        // Fetch
        public IActionResult viewSurvey()
        {
            return View(_appcontext.surveys.ToList());
        }

        // Delete
        public IActionResult surveyDelete(int Id)
        {
             Survey s = _appcontext.surveys.Find(Id);
            _appcontext.surveys.Remove(s);
            _appcontext.SaveChanges();
            return RedirectToAction("viewSurvey");
        }

        // Update
        public IActionResult surveyUpdate(int Id)
        {
            var mysurvey = _appcontext.surveys.Find(Id);
            return View(mysurvey);
        }

        // Update(insert)
        [HttpPost]
        public IActionResult surveyUpdate(Survey s)
        {
            var mysurveyupdate = _appcontext.surveys.Find(s.Id);

            if (mysurveyupdate != null)
            {
                mysurveyupdate.Title = s.Title;
                mysurveyupdate.Details = s.Details;
                mysurveyupdate.SurveyImage = s.SurveyImage;
            }
            _appcontext.SaveChanges();

            return RedirectToAction("viewSurvey");
        }

        // Facultay Work Start

        public IActionResult addFaculty()
        {
            return View();
        }

        // Insert + Img
        [HttpPost]
        public IActionResult addFaculty(faculty_ f)

        {
            String myfile = "";
            if (f.Photo != null)
            {
                String uploadFolder = Path.Combine(env.WebRootPath, "images");
                myfile = Guid.NewGuid().ToString() + "_" + f.Photo.FileName;
                String mergevalue = Path.Combine(uploadFolder, myfile);
                f.Photo.CopyTo(new FileStream(mergevalue, FileMode.Create));
                faculty data = new faculty
                {
                   Name = f.Name,
                   Email = f.Email,
                   Password  = f.Password,
                   Education = f.Education,
                   facultyimg = myfile
                };
                _appcontext.faculties.Add(data);
                _appcontext.SaveChanges();
                ModelState.Clear();
            }
            return View();

        }

        // Fetch
        public IActionResult ViewFaculty()
        {
            return View(_appcontext.faculties.ToList());
        }

        // Delete
        public IActionResult facultyDelete(int Id)
        {
            faculty f = _appcontext.faculties.Find(Id);
            _appcontext.faculties.Remove(f);
            _appcontext.SaveChanges();
            return RedirectToAction("ViewFaculty");
        }

        // Update
        public IActionResult FacultyUpdate(int Id)
        {
            var accountupdate = _appcontext.faculties.Find(Id);
            return View(accountupdate);
        }

        // Update(Insert)
        [HttpPost]
        public ActionResult FacultyUpdate(faculty f)
        {
            var updateaccount = _appcontext.faculties.Find(f.Id);
            if (updateaccount != null)
            {
                updateaccount.Name = f.Name;
                updateaccount.Email = f.Email;
                updateaccount.Password = f.Password;
                updateaccount.Education = f.Education;
                updateaccount.facultyimg = f.facultyimg;
            }
            _appcontext.SaveChanges();
            return RedirectToAction("ViewFaculty");
        }

        // Facultay Work End

        // Student Work Start

        // View
        public IActionResult AddStudent()
        {
            return View();
        }

        // Insert
        [HttpPost]
        public IActionResult AddStudent(Student s)
        {
            _appcontext.students.Add(s);
            _appcontext.SaveChanges();
            ModelState.Clear();
            return RedirectToAction("StudentLogin");
        }

        public IActionResult StudentLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult StudentLogin(Student s)
        {
            var studentdata = _appcontext.students.Where(data => data.Std_Roll_NO == s.Std_Roll_NO && data.Std_Name == s.Std_Name).FirstOrDefault();        
           
          if(studentdata != null)
                
            {
                return RedirectToAction("userdashboard");
            }
            return View();
        }

public IActionResult userdashboard()
        {
            return View();
        }

        // Fetch
        public IActionResult ViewStudent()
        {
            return View(_appcontext.students.ToList());
        }

        // Delete
        public IActionResult DeleteStudent(int Id)
        {

Environmental_survey/Views/admin/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/header_footer.cshtml";
}


<main>
    <!--? Hero Start -->
    <div class="slider-area2">
        <div class="slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap hero-cap2 pt-70">
                            <h2>About us</h2>
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","admin")">Home</a></li>
                                    <li class="breadcrumb-item"><a href="#">About</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!--? Visit Our Tailor Start -->
    <div class="visit-tailor-area fix">
        <!--Right Contents  -->
        <div class="tailor-offers"></div>
        <!-- left Contents -->
        <div class="tailor-details">
            <span>Our Mission</span>
            <h2>Our main goal is to protect animals</h2>
            <p>
                The automated process starts as soon as
                your clothes go into the machine. Duis cursus, mi quis
                viverra ornare, eros dolor interdum nulla, ut commodo
                diam libero vitae erat. Aenean faucibus nibh et justo
                cursus id rutrum lorem imperdiet. Nunc ut sem vitae
                risus tristique posuere.
            </p>
            <p class="pera-bottom">
                Interdum nulla, ut commodo diam libero vitae erat.
                Aenean faucibus nibh et justo cursus id rutrum lorem
                imperdiet. Nunc ut sem vitae risus tristique posuere.
            </p>
            <div class="footer-tittles">
                <p>CEO, Consulto</p>
                <h2>Capcilena Hanry</h2>
            </div>
        </div>
    </div>
    <!-- Visit Our Tailor End -->
    <!--? Services Area Start -->
    <div class="service-area section-padding30">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services1.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="" style="text-decoration:none;">Clean Water</a></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat active text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services2.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="" style="text-decoration:none;">Renewable energy</a></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services3.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="" style="text-decoration:none;">Protect animals</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Services Area End -->
    <!--? About Area Start -->
    <section class="support-company-area fix pb-padding">
        <div class="support-wrapper align-items-center">
            <div class="left-content">
                <!-- section tittle -->
                <div class="section-tittle section-tittle2 mb-30">
                    <span>Why You Should join us</span>
                    <h2>A lot of animals need protection</h2>
                </div>
                <div class="support-caption">
                    <p class="pera-top">
                        Interdum nulla, ut commodo diam libero vitae erat.
                        Aenean faucibus nibh et justo cursus id rutrum lorem
                        imperdiet. Nunc ut sem vitae risus tristique posuere.
                    </p>
                    <a href="@Url.Action("Contact","admin")" class="border-btn">Join Us Now</a>
                </div>
            </div>
            <div class="right-content">
                <!-- img -->
                <div class="right-img">
                    <img src="~/template/assets/img/gallery/safe_in.png" alt="">
                </div>
                <div class="support-img-cap text-center d-flex">
                    <div class="single-one">
                        <span>950</span>
                        <p>Poaching cases</p>
                    </div>
                    <div class="single-two">
                        <span>230</span>
                        <p>Volunteers worldwide</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Area End -->
</main>

Environmental_survey/Views/admin/Contact.cshtml
@model Environmental_survey.Models.contact

@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/header_footer.cshtml";
}


<!--? Hero Start -->
<div class="slider-area2">
    <div class="slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap hero-cap2 pt-70">
                        <h2>Contact Us</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index","admin")">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Contact Us</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero End -->
                   
<!--Contact Start-->
<section class="contact-page mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="contact-form">
                    <h3>Feel Free to Contact us</h3>
                    <ul class="cform">
                         <form asp-action="Contact" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <li class="half pr-15">

                            <input class="form-control" asp-for="Name" name="name" type="text" placeholder="Enter Your Name..." style="height: 45px; font-size: 12px;">
                                <span asp-validation-for="Name" class="text-danger"></span>
                           
                        </li>
                        <li class="half pl-15">

                            <input class="form-control" asp-for="Email" name="email" type="email" placeholder="Enter Your Email..." style="height: 45px; font-size: 12px;">
                                <span asp-validation-for="Email" class="text-danger"></span>
                            
                        </li>
        
                        <li class="full">

                            <input class="form-control" asp-for="Subject" name="subject" type="text" placeholder="Enter Your Subject.." style="height: 45px; font-size: 12px;">
                                <span asp-validation-for="Subject" class="text-danger"></span>
                            
                        </li>
                        <li class="full">

                            <textarea class="form-control" name="message" asp-for="Message" rows="15" placeholder="Enter Your Message..." style="font-size: 12px;"></textarea>
                                <span asp-validation-for="Message" class="text-danger"></span>
                          
                        </li>
                        <li class="full">
                            
                                <button type="submit" class="btn btn-success">Send</button>
                            
                        </li>
                        </form>
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                <div class="google-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3619.9026292694525!2d67.02166607520034!3d24.86717497792482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33e6b1566c46f%3A0x65318f4eb62c7aa8!2sAptech%20Computer%20Education%20Garden%20Center!5e0!3m2!1sen!2s!4v1702759222269!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
    <div class="container contact-info">
        <div class="row">
            <div class="col-md-12">
                <h3>Contact Information</h3>
            </div>
            <!--Contact Info Start-->
            <div class="col-md-4">
                <div class="c-info">
                    <h6>Address:</h6>
                    <p> 4700 Millenia Blvd # 175, Orlando, FL 32839, USA </p>
                </div>
            </div>
            <!--Contact Info End-->
            <!--Contact Info Start-->
            <div class="col-md-4">
                <div class="c-info">
                    <h6>Contact:</h6>
                    <p><strong>Phone:</strong> +1 321 2345 678-9</p>
                    <p><strong>Fax:</strong> +1 321 2345 876-7</p>
                </div>
            </div>
            <!--Contact Info End-->
            <!--Contact Info Start-->
            <div class="col-md-4">
                <div class="c-info">
                    <h6>For More Information:</h6>
                    <p><strong>Email:</strong> info@ecova.com</p>
                    <p>contact@ecova.com</p>
                </div>
            </div>
            <!--Contact Info End-->
        </div>
    </div>
</section>

Environmental_survey/Views/admin/Project.cshtml
@{
    ViewData["Title"] = "Project";
    Layout = "~/Views/Shared/header_footer.cshtml";
}


<main>
    <!--? Hero Start -->
    <div class="slider-area2">
        <div class="slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap hero-cap2 pt-70">
                            <h2>Projects</h2>
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","admin")">Home</a></li>
                                    <li class="breadcrumb-item"><a href="#">Projects</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!--? Our Cases Start -->
    <div class="our-cases-area section-padding30">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-10 col-lg-10 ">
                    <!-- Section Tittle -->
                    <div class="section-tittle text-center mb-80">
                        <h2>Every day 6,000 beavers perished</h2>
                        <p class="pl-20 pr-20">
                            Interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo
                            cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-cases mb-40">
                        <div class="cases-img">
                            <img src="~/template/assets/img/gallery/case1.png" alt="">
                        </div>
                        <div class="cases-caption">
                            <h3><a href="#">Wildlife in Danger</a></h3>
                            <p>
                                Interdum nulla, ut commodo diam libero vitae
                                erat. Aenean faucibus nibh et justo cursus
                                rutrum.
                            </p>
                            <!-- Progress Bar -->
                            <div class="single-skill mb-15">
                                <div class="bar-progress">
                                    <div id="bar1" class="barfiller">
                                        <div class="tipWrap">
                                            <span class="tip"></span>
                                        </div>
                                        <span class="fill" data-percentage="70"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- / progress -->
                            <div class="prices">
                                <p><span>47,589 of 74,574</span></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-cases mb-40">
                        <div class="cases-img">
                            <img src="~/template/assets/img/gallery/case2.png" alt="">
                        </div>
                        <div class="cases-caption">
                            <h3><a href="#">Our Green Projects</a></h3>
                            <p>
                                Interdum nulla, ut commodo diam libero vitae
                                erat. Aenean faucibus nibh et justo cursus
                                rutrum.
                            </p>
                            <!-- Progress Bar -->
                            <div class="single-skill mb-15">
                                <div class="bar-progress">
                                    <div id="bar2" class="barfiller">
                                        <div class="tipWrap">
                                            <span class="tip"></span>
                                        </div>
                                        <span class="fill" data-percentage="25"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="prices">
                                <p><span>47,589 of 74,574</span></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-cases">
                        <div class="cases-img">
                            <img src="~/template/assets/img/gallery/case3.png" alt="">
                        </div>
                        <div class="cases-caption">
                            <h3><a href="#">Wildlife in Danger</a></h3>
                            <p>
                                Interdum nulla, ut commodo diam libero vitae
                                erat. Aenean faucibus nibh et justo cursus
                                rutrum.
                            </p>
                            <!-- Progress Bar -->
                            <div class="single-skill mb-15">
                                <div class="bar-progress">
                                    <div id="bar3" class="barfiller">
                                        <div class="tipWrap">
                                            <span class="tip"></span>
                                        </div>
                                        <span class="fill" data-percentage="50"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="prices">
                                <p><span>47,589 of 74,574</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Our Cases End -->
    <!--? About Area Start -->
    <section class="support-company-area fix ">
        <div class="support-wrapper align-items-center">
            <div class="left-content">
                <!-- section tittle -->
                <div class="section-tittle section-tittle2 mb-30">
                    <span>Why You Should join us</span>
                    <h2>A lot of animals need protection</h2>
                </div>
                <div class="support-caption">
                    <p class="pera-top">
                        Interdum nulla, ut commodo diam libero vitae erat.
                        Aenean faucibus nibh et justo cursus id rutrum lorem
                        imperdiet. Nunc ut sem vitae risus tristique posuere.
                    </p>
                    <a href="@Url.Action("Contact","admin")" class="border-btn">Join Us Now</a>
                </div>
            </div>
            <div class="right-content">
                <!-- img -->
                <div class="right-img">
                    <img src="~/template/assets/img/gallery/safe_in.png" alt="">
                </div>
                <div class="support-img-cap text-center d-flex">
                    <div class="single-one">
                        <span>950</span>
                        <p>Poaching cases</p>
                    </div>
                    <div class="single-two">
                        <span>230</span>
                        <p>Volunteers worldwide</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Area End -->
    <!--? Services Area Start -->
    <div class="service-area section-padding30">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services1.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="" style="text-decoration:none;">Clean Water</a></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat active text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services2.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="" style="text-decoration:none;">Renewable energy</a></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-11">
                    <div class="single-cat text-center mb-30">
                        <div class="cat-icon">
                            <img src="~/template/assets/img/gallery/services3.png" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="#">Protect animals</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Services Area End -->
</main>

Environmental_survey/Views/admin/userdashboard.cshtml
@{
    ViewData["Title"] = "userdashboard";
    Layout = "~/Views/Shared/User.cshtml";
}

<div class="container">
    <center>
        <h1>Welcom To Student Dashboard</h1>
    </center>
    
    <img src="~/dashboard/assets/images/profile/user-1.jpg" width="100%" height="600px"/>
</div>